# User config
author: "Derivas"
tagline: ""
description: "Acreditamos no poder de educar por meio de jogos e simulações, capacitando agentes capazes de mudar a política brasileira em prol do campo democrático popular."
keywords: "Jogos, Games, Jogos políticos, simulações, interativo"
email: "bolitto.walter@gmail.com"
twitter: "https://twitter.com/derivas_"
github: "https://github.com/bolitto"
mastodon: "https://mastodon.social/@derivas"

# Site config
baseurl: "http://derivas.cc"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
