# User config
author: "Derivas"
tagline: ""
description: "Derivas é um instrumento de experimentações engajadas no campo dos videogames. Investigando o papel da educação através de jogos e simulações, é possível construir críticas e utopias de forma popular e democrática."
keywords: "Jogos, Games, Jogos políticos, simulações, interativo"
email: "bolitto.walter@gmail.com"
twitter: "https://twitter.com/derivascc"
facebook: "https://facebook.com/derivascc"
github: "https://github.com/bolitto"
mastodon: "https://mastodon.social/@derivas"

# Site config
baseurl: "http://derivas.cc"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
